<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>3aada3c3-44d9-44cb-8e25-9be67af78b8d</UserSecretsId>
      
    <BlazorRoutesGenerator_NameOverrides>
        SchulCloud.Frontend.Components.Pages.Account.Overview=AccountOverview
        SchulCloud.Frontend.Components.Pages.Account.Settings=AccountSettings
        SchulCloud.Frontend.Components.Pages.Account.Security.Overview=SecurityOverview
        SchulCloud.Frontend.Components.Pages.Account.Security.TwoFactor.Authenticator=TwoFactorAuthenticator
        SchulCloud.Frontend.Components.Pages.Account.Security.TwoFactor.Recovery=TwoFactorRecovery
    </BlazorRoutesGenerator_NameOverrides>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" />
    <PackageReference Include="BlazorGoogleMaps" />
    <PackageReference Include="Fido2.AspNet" />
    <PackageReference Include="Humanizer.Core" />
    <PackageReference Include="Humanizer.Core.de" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="MudBlazor.FontIcons.MaterialSymbols" />
    <PackageReference Include="MudBlazor.Translations" />
    <PackageReference Include="MyCSharp.HttpUserAgentParser" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Quartz" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="Quartz.AspNetCore"  />
    <PackageReference Include="Suiram1.BlazorRoutesGenerator" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MailKit.Client\MailKit.Client.csproj" />
    <ProjectReference Include="..\SchulCloud.Authorization\SchulCloud.Authorization.csproj" />
    <ProjectReference Include="..\SchulCloud.FileStorage.S3\SchulCloud.FileStorage.S3.csproj" />
    <ProjectReference Include="..\SchulCloud.Identity\SchulCloud.Identity.csproj" />
    <ProjectReference Include="..\SchulCloud.Database\SchulCloud.Database.csproj" />
    <ProjectReference Include="..\SchulCloud.ServiceDefaults\SchulCloud.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
	<Content Update="package-lock.json" CopyToOutputDirectory="Never" />
	<Content Update="package.json" CopyToOutputDirectory="Never" />
	<Content Update="tsconfig.json" CopyToOutputDirectory="Never" />
  </ItemGroup>

  <!-- Exclude every else web asset excluding _content -->
  <ItemGroup>
    <Content Remove="wwwroot/**" />
    <Content Include="wwwroot/_content/**/*" />
    <None Include="wwwroot/**/*" />
  </ItemGroup>

  <!-- Copies assets from wwwroot/ to wwwroot/_content/ -->
  <Target Name="_SetupWebAssets" AfterTargets="BeforeBuild">
	<ItemGroup>
      <WebAssets Include="wwwroot\**\*" Exclude="wwwroot\_content\**\*" />
    </ItemGroup>
	  
    <Copy SourceFiles="@(WebAssets)" DestinationFolder="wwwroot\_content\%(RecursiveDir)" />
  </Target>

  <!-- Copies isolated css file into the asset structure -->
  <Target Name="_CopyIsolatedCSS" AfterTargets="Build">
    <Copy SourceFiles="$(IntermediateOutputPath)scopedcss\bundle\$(PackageId).styles.css" DestinationFiles="wwwroot\_content\$(PackageId).styles.css" />
  </Target>

  <Target Name="_TranspileTypeScript" AfterTargets="Build">
      
      <!-- Verify whether npm and npx are available -->
      <Exec Command="npm --version" IgnoreExitCode="true" 
            StandardOutputImportance="Low" StandardErrorImportance="Low">
          <Output TaskParameter="ExitCode" PropertyName="NpmExitCode" />
      </Exec>
      <Exec Command="npx --version" IgnoreExitCode="true"
            StandardOutputImportance="Low" StandardErrorImportance="Low">
          <Output TaskParameter="ExitCode" PropertyName="NpxExitCode" />
      </Exec>
      <Error Condition="'$(NpmExitCode)' != '0'" Text="npm isn't installed or not in the PATH. Please install Node.Js" />
      <Error Condition="'$(NpxExitCode)' != '0'" Text="npx isn't installed or not in the PATH. Please install Node.js" />
      
    <Exec Command="npm install" WorkingDirectory=".\" StandardOutputImportance="Low" StandardErrorImportance="Low" />
    <Exec Command="npx rollup -c" WorkingDirectory=".\" EnvironmentVariables="NODE_ENV=$(Configuration);FORCE_COLOR=0" />
  </Target>
    
</Project>