<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>1592926b-ec5c-485b-87d2-225d0007f632</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Instrumentation.Quartz" />
    <PackageReference Include="Quartz.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchulCloud.Database\SchulCloud.Database.csproj" />
    <ProjectReference Include="..\SchulCloud.ServiceDefaults\SchulCloud.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
