<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fido2" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="MyCSharp.HttpUserAgentParser" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchulCloud.Authorization\SchulCloud.Authorization.csproj" />
    <ProjectReference Include="..\SchulCloud.FileStorage\SchulCloud.FileStorage.csproj" />
  </ItemGroup>
</Project>
