<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AwsS3.Client\AwsS3.Client.csproj" />
    <ProjectReference Include="..\SchulCloud.FileStorage\SchulCloud.FileStorage.csproj" />
  </ItemGroup>

</Project>
